In [1]:
import os # 경고 대응
os.environ['OMP_NUM_THREADS'] = '1'

import pandas as pd
import numpy as np

df = pd.read_csv("cal112_kind_of_average.csv")

df

,Unnamed: 0,지역,5대범죄 건수 평균,인구밀도 평균,112신고 건수 평균,여성 가구원수 평균,cctv수 평균,가로등수 평균
0,0,강남구,7543.571429,6736.714286,170421.42860,261914.57140,869.857143,13837.285710
1,1,강동구,4163.714286,13509.142860,89579.71429,212260.00000,319.714286,7724.428571
2,2,강북구,3460.714286,11169.571430,74903.42857,154574.00000,428.428571,4388.285714
3,3,강서구,4862.000000,18163.000000,114848.00000,287358.85710,323.142857,7849.571429
4,4,관악구,5372.428571,21519.571430,112705.00000,253621.85710,536.428571,5190.142857
5,5,광진구,4355.857143,25591.714290,86648.57143,181476.85710,404.571429,4857.142857
6,6,구로구,4726.428571,22002.714290,86006.57143,212753.42860,429.142857,7669.285714
7,7,금천구,3160.857143,18462.857140,63704.28571,120722.14290,308.142857,5243.000000
8,8,노원구,4172.857143,13607.428570,89983.42857,265683.71430,309.142857,9302.285714
9,9,도봉구,2214.142857,16407.000000,54898.85714,162298.71430,233.285714,4499.000000
10,10,동대문구,3887.714286,15459.428570,28858.42857,177716.14290,370.571429,8152.285714
11,11,동작구,3280.285714,16460.857140,69205.42857,199861.57140,244.714286,5542.857143
12,12,마포구,4892.428571,18313.285710,107486.28570,190437.28570,328.857143,8084.571429
13,13,서대문구,3051.857143,16220.285710,64242.42857,162843.14290,258.428571,5910.142857
14,14,서초구,4809.428571,26957.714290,98123.57143,205641.28570,550.285714,12161.285710
15,15,성동구,2656.285714,14388.142860,57321.42857,147371.14290,458.142857,5860.714286
16,16,성북구,3175.571429,21849.714290,75245.14286,223697.42860,577.714286,5478.000000
17,17,송파구,5724.714286,19342.571430,127502.57140,317456.42860,374.714286,13093.428570
18,18,양천구,3640.285714,16527.714290,74413.28571,219399.57140,444.714286,7816.571429
19,19,영등포구,5744.857143,24884.285710,113342.14290,195884.14290,426.714286,9287.285714
20,20,용산구,3441.571429,17499.857140,73440.85714,113818.57140,306.714286,7433.571429
21,21,은평구,3890.428571,9324.000000,86552.28571,233652.42860,534.000000,6441.285714
22,22,종로구,3795.857143,14084.571430,74265.71429,77940.71429,100.714286,8887.428571
23,23,중구,4050.142857,19811.428570,128958.71430,65017.00000,307.571429,8634.428571
24,24,중랑구,4328.142857,18328.714290,87161.00000,193835.57140,435.000000,5947.142857

In [2]:
df1 = df.drop(['Unnamed: 0'], axis=1) 
df2 = df1[['지역','5대범죄 건수 평균', '인구밀도 평균', '여성 가구원수 평균', 'cctv수 평균', '가로등수 평균', '112신고 건수 평균']]
df2

,지역,5대범죄 건수 평균,인구밀도 평균,여성 가구원수 평균,cctv수 평균,가로등수 평균,112신고 건수 평균
0,강남구,7543.571429,6736.714286,261914.57140,869.857143,13837.285710,170421.42860
1,강동구,4163.714286,13509.142860,212260.00000,319.714286,7724.428571,89579.71429
2,강북구,3460.714286,11169.571430,154574.00000,428.428571,4388.285714,74903.42857
3,강서구,4862.000000,18163.000000,287358.85710,323.142857,7849.571429,114848.00000
4,관악구,5372.428571,21519.571430,253621.85710,536.428571,5190.142857,112705.00000
5,광진구,4355.857143,25591.714290,181476.85710,404.571429,4857.142857,86648.57143
6,구로구,4726.428571,22002.714290,212753.42860,429.142857,7669.285714,86006.57143
7,금천구,3160.857143,18462.857140,120722.14290,308.142857,5243.000000,63704.28571
8,노원구,4172.857143,13607.428570,265683.71430,309.142857,9302.285714,89983.42857
9,도봉구,2214.142857,16407.000000,162298.71430,233.285714,4499.000000,54898.85714
10,동대문구,3887.714286,15459.428570,177716.14290,370.571429,8152.285714,28858.42857
11,동작구,3280.285714,16460.857140,199861.57140,244.714286,5542.857143,69205.42857
12,마포구,4892.428571,18313.285710,190437.28570,328.857143,8084.571429,107486.28570
13,서대문구,3051.857143,16220.285710,162843.14290,258.428571,5910.142857,64242.42857
14,서초구,4809.428571,26957.714290,205641.28570,550.285714,12161.285710,98123.57143
15,성동구,2656.285714,14388.142860,147371.14290,458.142857,5860.714286,57321.42857
16,성북구,3175.571429,21849.714290,223697.42860,577.714286,5478.000000,75245.14286
17,송파구,5724.714286,19342.571430,317456.42860,374.714286,13093.428570,127502.57140
18,양천구,3640.285714,16527.714290,219399.57140,444.714286,7816.571429,74413.28571
19,영등포구,5744.857143,24884.285710,195884.14290,426.714286,9287.285714,113342.14290
20,용산구,3441.571429,17499.857140,113818.57140,306.714286,7433.571429,73440.85714
21,은평구,3890.428571,9324.000000,233652.42860,534.000000,6441.285714,86552.28571
22,종로구,3795.857143,14084.571430,77940.71429,100.714286,8887.428571,74265.71429
23,중구,4050.142857,19811.428570,65017.00000,307.571429,8634.428571,128958.71430
24,중랑구,4328.142857,18328.714290,193835.57140,435.000000,5947.142857,87161.00000

In [3]:
where = pd.get_dummies(df2['지역'])
df3 = df2.drop('지역', axis=1)
where

,강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,도봉구,...,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [4]:
df4 = df3.join(where)
df4

,5대범죄 건수 평균,인구밀도 평균,여성 가구원수 평균,cctv수 평균,가로등수 평균,112신고 건수 평균,강남구,강동구,강북구,강서구,...,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구
0,7543.571429,6736.714286,261914.57140,869.857143,13837.285710,170421.42860,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4163.714286,13509.142860,212260.00000,319.714286,7724.428571,89579.71429,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3460.714286,11169.571430,154574.00000,428.428571,4388.285714,74903.42857,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,4862.000000,18163.000000,287358.85710,323.142857,7849.571429,114848.00000,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,5372.428571,21519.571430,253621.85710,536.428571,5190.142857,112705.00000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,4355.857143,25591.714290,181476.85710,404.571429,4857.142857,86648.57143,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,4726.428571,22002.714290,212753.42860,429.142857,7669.285714,86006.57143,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,3160.857143,18462.857140,120722.14290,308.142857,5243.000000,63704.28571,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,4172.857143,13607.428570,265683.71430,309.142857,9302.285714,89983.42857,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,2214.142857,16407.000000,162298.71430,233.285714,4499.000000,54898.85714,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,3887.714286,15459.428570,177716.14290,370.571429,8152.285714,28858.42857,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,3280.285714,16460.857140,199861.57140,244.714286,5542.857143,69205.42857,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,4892.428571,18313.285710,190437.28570,328.857143,8084.571429,107486.28570,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,3051.857143,16220.285710,162843.14290,258.428571,5910.142857,64242.42857,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,4809.428571,26957.714290,205641.28570,550.285714,12161.285710,98123.57143,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,2656.285714,14388.142860,147371.14290,458.142857,5860.714286,57321.42857,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
16,3175.571429,21849.714290,223697.42860,577.714286,5478.000000,75245.14286,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,5724.714286,19342.571430,317456.42860,374.714286,13093.428570,127502.57140,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,3640.285714,16527.714290,219399.57140,444.714286,7816.571429,74413.28571,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
19,5744.857143,24884.285710,195884.14290,426.714286,9287.285714,113342.14290,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
20,3441.571429,17499.857140,113818.57140,306.714286,7433.571429,73440.85714,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
21,3890.428571,9324.000000,233652.42860,534.000000,6441.285714,86552.28571,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
22,3795.857143,14084.571430,77940.71429,100.714286,8887.428571,74265.71429,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,4050.142857,19811.428570,65017.00000,307.571429,8634.428571,128958.71430,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
24,4328.142857,18328.714290,193835.57140,435.000000,5947.142857,87161.00000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
from sklearn.linear_model import LinearRegression 
from sklearn import linear_model

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

In [6]:
X = df4[df4.columns.difference(['112신고 건수 평균'])]
y = df4['112신고 건수 평균']

#검증(test)는 20%로 한다. = test_size=0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=121)

In [7]:

# 회귀 분석 객체 생성(선형 회귀 모델 생성)
lr = linear_model.LinearRegression()

#fit()는 기울기와 절편을 전달하기 위함.
model = lr.fit(X_train, y_train)

# 학습된 계수를 출력합니다.
print(lr.coef_)

# 상수항을 출력합니다.
print(lr.intercept_)

[ 2.14277455e+01 -2.27390722e+00  1.04355133e+00  2.78781219e+02
 -2.15679647e+03 -2.09452301e+03  1.40986246e+04  4.24409929e+03
 -1.59120442e+03 -1.32565149e+04  3.41060513e-13 -8.88151903e+02
  7.03061634e+03 -1.81898940e-12  0.00000000e+00  1.05972219e+03
 -3.05655591e+03 -5.23715534e+03 -2.67859064e+03  0.00000000e+00
  5.00694406e+03  0.00000000e+00 -5.02183985e-02 -8.85980629e+03
 -5.51800737e+03  1.50275369e+03 -4.94487968e-01 -1.77608400e+04
  3.44006366e+04 -4.52403166e+03]
12523.129305726543

In [11]:
y_predicted=model.predict(X)
print(y_predicted)

[86923.64382454 62933.22390256 78481.3488171  69863.63141853
 69831.68982707]

In [9]:
df4["예측"] = y_predicted
df4

ValueError: Length of values (5) does not match length of index (25)

In [ ]:
df4[['112신고 건수 평균', '예측']]

In [ ]:
print(model.score(X_train, y_train)) # train R2 score를 출력합니다.
print(model.score(X_test, y_test)) # test R2 score를 출력합니다.